CREATE TABLE `EMPLOYEE_PROJECT` (
  `EMPLOYEE_ID` INT(11) NOT NULL,
  `PROJECT_ID` INT(11) NOT NULL,
  PRIMARY KEY (`EMPLOYEE_ID`,`PROJECT_ID`),
  CONSTRAINT `EMPLOYEE_PROJECT_IBFK_1` 
   FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `EMPLOYEE` (`ID`),
  CONSTRAINT `EMPLOYEE_PROJECT_IBFK_2` 
   FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`ID`)
)